#!/bin/bash
#

#  Nombre script: ganesha-del-alumnes-grup.en_pruebas
#  Version: ganesha 02-03-2022
#  Verificado: NO
# 
#  Parámetros de entrada: 
#    $1="usuarios" 
#    $2="asignatura"
#    $3="grupo_asignatura" 
#    $4="vaciar_grupo" (TRUE/Cualquier otro valor diferente de "TRUE" será falso)
#
#  Salida en STDOUT (no STDERR): 
#    {
#    "codi":"<codi>", 
#    "message":"<mensaje>", 
#    "json": { "usuario":"<usuario>", "asignatura":"<asignatura>", "grupo_asignatura":"<grupo_asignatura>" }
#     }
#
#  Operaciones:
#	1.- Borrar "usuario" del grupo "grupo_asignatura" local
#	2.- Borrar "usuario" al grupo "asignatura" local  
#	3.- Mostrar codigo de salida correcta o incorrecta según caso.
#
#  Codigos de error:
#	505 - El directorio de la asignatura no existe
#	506 - El directorio del grupo de la asignatura no existe
#	507 - El grupo local de la asignatura no existe
#	508 - El grupo local del grupo de la asignatura no existe
#	520 - El alumno no puede borrarse del grupo local del grupo de la asignatura, motivo desconocido
#	521 - El alumno no puede borrarse del grupo local de la asignatura, motivo desconocido
#	537 - El directorio del grupo de la asingatura no puede vaciarse, motivo desconocido
#	599 - Faltan parametros

source /usr/local/sbin/ganesha-config.sh
usuarios="$1"
asignatura="$2"
grupo_asignatura="$3"
vaciar_grupo="$4"

salida()
{ 
    echo "{" 
    echo "\"codi\":\"$2\"," 
    if [ "$2" -eq "200" ]; then
       echo "\"message\":\"$1\","
    else
       codigo_error="codigo_$2"
       echo "\"message\":\"${!codigo_error}\","
    fi
    echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\", \"grupo_asignatura\":\"$5\"}" ; 
    echo "},"
} 


 echo "["

	error="0"
	
	if [[ $usuarios && $asignatura && $grupo_asignatura ]]; then

	  for usuario in $usuarios
              do
                error="0"

# Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són validas de antemano

               if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
               if [ ! -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then error=506; fi
               if [ ! $(getent group "$asignatura") ]; then error=507; fi
               if [ ! $(getent group "$grupo_asignatura") ]; then error=508; fi

# Fin control de errores fatales


		if [ "$error" -lt "500" ]; then /usr/sbin/deluser $usuario $grupo_asignatura 2>/dev/null 1>/dev/null || error=520; fi 

                if [ "$error" -lt "500" ] ; then     
		
		existe_en_grupo="0"
 
                 cd $HOME_GANESHA"/$asignatura"
                     for grupo_asignatura_usuario in $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do

                       if [ "$(grep "$grupo_asignatura_usuario" /etc/group | grep "$usuario," | wc -l)" -gt "0" ] || [ "$(grep "$grupo_asignatura_usuario" /etc/group | grep ",$usuario" | wc -l)" -gt "0" ] ; then
                            
#                           echo  "El usuario está al menos en el grupo $grupo_asignatura_usuario. Abortando";  existe_en_grupo="1" 
			   existe_en_grupo="1"
                           break
                       fi

                     done

                     if [ "$existe_en_grupo" -lt "1" ] ; then
#                           echo "El usuario $usuario se puede borrar del grupo de asignatura $asignatura."  
                           /usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error=521
                     fi

		fi

        	if [ "$error" -gt "500" ]; then
	             txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura" "$grupo_asignatura")"
	          else
	             txt_salida="$txt_salida$(salida "OK" "200" "$usuario" "$asignatura" "$grupo_asignatura")"
	        fi

	  done
	
	 if [ "$vaciar_grupo" = "TRUE" ] && [ "$error" -lt "500" ]; then
		if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then
		   /bin/rm -rf "$HOME_GANESHA/$asignatura/$grupo_asignatura/"* 2>/dev/null 1>/dev/null || error=537;
		   if [ "$error" -gt "500" ]; then
			 txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuarios" "$asignatura" "$grupo_asignatura")"
		   fi
		fi
 	 fi

  	else
		error=599
		txt_salida=$(salida "ERROR" "$error")
	fi


    txt_salida=${txt_salida::-1}
    echo "$txt_salida"
    echo "]"

