#!/bin/bash
#

#  Nombre script: ganesha-del-profe-assignatura
# 
#  Parámetros de entrada: 
#    $1="nius profesores" 
#    $2="asignatura"
#
#  Salida en STDOUT (no STDERR): 
#    {
#    "codi":<codi>, 
#    "message":"<mensaje>", 
#    "json": { "usuario":"<usuario>", "asignatura":"<asignatura>", "grupo_asignatura":"<grupo_asignatura>" }
#
#  Operaciones:
#	1.- Borrar "usuario" del grupo "asignatura" local
#	2.- Borrar "usuario" de todos los "grupo_asignatura" local  
#	3.- Mostrar codigo de salida correcta o incorrecta según caso.
#
#  Codigos de salida:
#	201 - El usuario se ha borrado del grupo de assignatura principal, pero no de todos los grupos_asignatura
#       501 - El usuario o grupo asignatura no existe (1.- El usuario no existe. 2.- El grupo "asignatura" no existe).
#	502 - El grupo "grupo_asignatura" no existe
#	503 - El directorio de asignatura no existe
#	510 - Faltan parametros

source /usr/local/sbin/ganesha-config.sh
usuarios="$1"
asignatura="$2"

salida()
{ 
    echo "{" 
    echo "\"codi\":$2," 
    echo "\"message\":\"$1\"," 
    echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\"}" ; 
    echo "},"
} 

 echo "["

	if [[ $usuarios && $asignatura ]]; then
	   for usuario in $usuarios
	      do
	        error="0"

		if [ -d "$HOME_GANESHA/$asignatura" ]; then /usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error="501"; else error="503"; fi

		if [ "$error" -lt "500" ] && [ -d "$HOME_GANESHA/$asignatura" ]; then
		 	cd $HOME_GANESHA"/$asignatura"
			     for directorio_grupo in  $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
				/usr/sbin/deluser $usuario $directorio_grupo 2>/dev/null 1>/dev/null || error="201";
		     	     done
		fi
	
	        if [ "$error" -gt "500" ]; then
        	     txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura")"

	        else
	             txt_salida="$txt_salida$(salida "Borrado el profesor \\\"$usuario\\\" de la asignatura \\\"$asignatura\\\"" "200" "$usuario" "$asignatura")"
	        fi

	      done
  	else
		error=510
		txt_salida=$(salida "ERROR" "$error")
	fi


    txt_salida=${txt_salida::-1}
    echo "$txt_salida"
    echo "]"

