#!/bin/bash
#

HOME_GANESHA="/home/samba/assignatures"

codigo_200="Comanda executada correctament"
codigo_501="Usuari inexistent o no pot afegir-se al grup local"
codigo_502="El grup local assignatura no es pot crear, motiu desconegut"
codigo_503="El directori de l assignatura no es pot crear, ya existeix"
codigo_504="No ha estat possible canviar els permisos del directori de l assignatura, motiu desconegut"
codigo_505="El directori de l assignatura no existeix"
codigo_506="El directori del grup de l assignatura no existeix"
codigo_507="El grup local de l assignatura no existeix"
codigo_508="El grup local del grup de l assignatura no existeix"
codigo_509="No es pot afegir l usuari al grup local de l assignatura, motiu desconegut"
codigo_510="No es pot afegir l usuari al grup local del grup de l assignatura, motiu desconegut"
codigo_511="El directori de l assignatura no es pot crear, motiu desconegut"
codigo_512="El grup local d assignatura no es pot crear, ja existeix"
codigo_513="El professor no pot afegir-se al grup local d assignatura, motiu desconegut"
codigo_514="El directori del grup de l assignatura no es pot crear, ja existeix"
codigo_515="El grup local del grup de l assignatura no es pot crear, ja existeix"
codigo_516="El professor no pot afegir-se al grup local del grup de l assignatura, motiu desconegut"
codigo_517="El directori del grup de l assignatura no es pot crear, motiu desconegut"
codigo_518="El grup local del grup de l assignatura no es pot crear, motiu desconegut"
codigo_519="No ha estat possible canviar els permisos del directori del grup de l assignatura, motiu desconegut"
codigo_520="L alumne no es pot treure del grup local del grup de l assignatura, motiu desconegut"
codigo_521="L alumne no es pot treure del grup local de l assignatura, motiu desconegut"
codigo_522="El directori del grup de l assignatura no es pot renombrar, ja existeix un directori amb el mateix nom"
codigo_523="El grup local del grup de l assignatura no es pot renombrar, ja existeix un grup local amb el mateix nom"
codigo_524="El grup local del grup de l assignatura no es pot renombrar, motiu desconegut"
codigo_525="El directori del grup de l assignatura no es pot renombrar, motiu desconegut"
codigo_526="La quota del grup de l assignatura no es pot canviar, motiu desconegut"
codigo_527="El directori o el grup local del grup de l assignatura no existeix, o el nou directori o grup local del grup de l assignatura ja existeix"
codigo_528="No ha estat possible trobar les dades d espai del filesystem, motiu desconegut"
codigo_529="No existeix el directori amb el filesystem, o no està muntat"
codigo_530="Un directori del grup de l assignatura no es pot eliminar, motiu desconegut"
codigo_531="La quota d un grup de l assignatura no es pot eliminar, motiu desconegut"
codigo_532="El grup local d un grup de l assignatura no es pot eliminar, motiu desconegut"
codigo_533="La quota de l assignatura no es pot eliminar, motiu desconegut"
codigo_534="El directori de l assignatura no es pot eliminar, motiu desconegut"
codigo_535="El grup local de l assignatura no es pot eliminar, motiu desconegut"
codigo_536="El directori del grup de l assignatura no es pot eliminar, motiu desconegut"
codigo_537="El directori del grup de l assignatura no es pot buidar, motiu desconegut"
codigo_538="El nom de l assignatura és massa llarg, màxim 15 caràcters"
codigo_539="El nom de l assignatura conté caràcters no vàlids, només pot contenir lletres en minúscula, nombres i –"
codigo_540="L usuari ha estat eliminat del grup d assignatura principal, però no de tots els grups de l assignatura"
codigo_599="Manquen paràmetres a la comanda"

#codigo_200="Todo correcto"
#
#codigo_501="El usuario no existe o no puede añadirse al grupo local"
#codigo_502="El grupo local asignatura no se puede crear, motivo desconocido"
#codigo_503="El directorio de la asignatura no se puede crear, ya existe"
#codigo_504="No se han podido cambiar los permisos del directorio de la asignatura, motivo desconocido"
#codigo_505="El directorio de la asignatura no existe"
#codigo_506="El directorio del grupo de la asignatura no existe"
#codigo_507="El grupo local de la asignatura no existe"
#codigo_508="El grupo local del grupo de la asignatura no existe"
#codigo_509="No se puede añadir el usuario al grupo local de la asignatura, motivo desconocido"
#codigo_510="No se puede añadir el usuario al grupo local del grupo de la asignatura, motivo desconocido"
#codigo_511="El directorio de la asignatura no se puede crear, motivo desconocido"
#codigo_512="El grupo local de asignatura no se puede crear, ya existe"
#codigo_513="El profesor no puede añadirse al grupo local de asignatura, motivo desconocido"
#codigo_514="El directorio del grupo de la asignatura no se puede crear, ya existe"
#codigo_515="El grupo local del grupo de la asignatura no se puede crear, ya existe"
#codigo_516="El profesor no puede añadirse al grupo local del grupo de la asignatura, motivo desconocido"
#codigo_517="El directorio del grupo de la asignatura no se puede crear, motivo desconocido"
#codigo_518="El grupo local del grupo de la asignatura no se puede crear, motivo desconocido"
#codigo_519="No se han podido cambiar los permisos del directorio del grupo de la asignatura, motivo desconocido"
#codigo_520="El alumno no puede borrarse del grupo local del grupo de la asignatura, motivo desconocido"
#codigo_521="El alumno no puede borrarse del grupo local de la asignatura, motivo desconocido"
#codigo_522="El directorio del grupo de la asignatura no se puede renombrar, ya existe un directorio con el mismo nombre"
#codigo_523="El grupo local del grupo de la asignatura no se puede renombrar, ya existe un grupo local con el mismo nombre"
#codigo_524="El grupo local del grupo de la asignatura no se puede renombrar, motivo desconocido"
#codigo_525="El directorio del grupo de la asignatura no se puede renombrar, motivo desconocido"
#codigo_526="La quota del grupo de la asignatura no se puede cambiar, motivo desconocido"
#codigo_527="El directorio o el grupo local del grupo de la asignatura no existe, o el nuevo directorio o grupo local del grupo de la asignatura ya exite"
#codigo_528="No se ha podido encontrar los datos de espacio del filesystem, motivo desconocido"
#codigo_529="No existe el directorio con el filesystem, o no está montado"
#codigo_530="Un directorio del grupo de la asignatura no puede borrarse, motivo desconocido"
#codigo_531="La quota de un grupo de la asignatura no puede borrarse, motivo desconocido"
#codigo_532="El grupo local de un grupo de la asignatura no puede borrarse, motivo desconocido"
#codigo_533="La quota de la asignatura no puede borrarse, motivo desconocido"
#codigo_534="El directorio de la asignatura no puede borrarse, motivo desconocido"
#codigo_535="El grupo local de la asignatura no puede borrarse, motivo desconocido"
#codigo_536="El directorio del grupo de la asignatura no puede borrarse, motivo desconocido"
#codigo_537="El directorio del grupo de la asingatura no puede vaciarse, motivo desconocido"
#codigo_538="El nombre de asignatura es demasiado largo, máximo 15 carácteres"
#codigo_539="El nombre de la asignatura contiene carácteres no válidos, solo se permiten letras en minúscula, números y -"
#codigo_540="El usuario se ha borrado del grupo de assignatura principal, pero no de todos los grupos de la asignatura"
#
#codigo_599="Faltan parámetros"


