#!/bin/bash
#

#  Nombre script: ganesha-add-assignatura
#
#  Parámetros de entrada:
#   $1=asignatura
#
#  Salida en STDOUT (no STDERR):
#    {
#    "codi":<codi>,
#    "message":"<mensaje>",
#    "json": [ { "codi_assignatura":"<codi>" } ]
#    }
#
#  Operaciones:
#	1.- Crear directorio de assignatura en la ruta definida en "ganesha-config.sh"
#	2.- Crear grupo local de assignatura
#	3.- Assignar permisos directorio de assignatura
#	4.- Mostrar codigo de salida correcta o incorrecta según caso.
#
#  Codigos de error:
#
#	502 - El grupo local asignatura no se puede crear, motivo desconocido
#       503 - El directorio de la asignatura no se puede crear, ya existe
#	504 - No se han podido cambiar los permisos del directorio de la asignatura, motivo desconocido
#	511 - El directorio de la asignatura no se puede crear, motivo desconocido
#	512 - El grupo local asignatura no se puede crear, ya existe
#	538 - El nombre de asignatura es demasiado largo, máximo 15 carácteres
#       539 - El nombre de la asignatura contiene carácteres no válidos, solo se permiten letras en minúscula, números y -
#	599 - Faltan parámetros

source /usr/local/sbin/ganesha-config.sh
asignatura="$1"

salida()
{
  echo "{"
  echo "\"codi\":$2,"
  if [ "$2" -eq "200" ]; then
          echo "\"message\":\"$1\","
      else
          codigo_error="codigo_$2"
          echo "\"message\":\"${!codigo_error}\","
  fi
  echo "\"json\": [ {\"codi_assignatura\":\"$asignatura\"} ]" ;
  echo "}"
}

	error="0"

	if [ $asignatura ]; then

# Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són válidas de antemano

		if [ ${#asignatura} -ge 15 ]; then salida "ERROR" "538"; exit; fi
    case "$asignatura" in
      (*[![abcdefghijklmnopqrstuvwxyz0123456789-]*) salida "ERROR" "539"; exit ;;
    esac
    if [ -d "$HOME_GANESHA/$asignatura" ]; then salida "ERROR" "503"; exit; fi
    if [ $(getent group "$asignatura") ]; then salida "ERROR" "512"; exit; fi

# Fin control de errores fatales

    if [ -d "$HOME_GANESHA/$asignatura" ]; then error=503; else /bin/mkdir -m 0750  $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error=511; fi
    if [ "$error" -lt "500" ]; then if [ $(getent group "$asignatura") ]; then error=512; else /usr/sbin/addgroup "$asignatura" 2>/dev/null 1>/dev/null || error=502; fi; fi
    if [ "$error" -lt "500" ]; then /bin/chown root:"$asignatura" $HOME_GANESHA"/$asignatura"  2>/dev/null 1>/dev/null || error=504; fi
  else
    error="599"
  fi

  if [ "$error" -gt "500" ]; then
    salida "ERROR" "$error"
  else
    salida "Assignatura creada correctament." "200"
  fi
