#!/bin/bash
#

#  Nombre script: ganesha-del-profe-assignatura
# 
#  Parámetros de entrada: 
#    $1="nius profesores" 
#    $2="asignatura"
#
#  Salida en STDOUT (no STDERR): 
#    {
#    "codi":<codi>, 
#    "message":"<mensaje>", 
#    "json": { "usuario":"<usuario>", "asignatura":"<asignatura>", "grupo_asignatura":"<grupo_asignatura>" }
#
#  Operaciones:
#	1.- Borrar "usuario" del grupo "asignatura" local
#	2.- Borrar "usuario" de todos los "grupo_asignatura" local  
#	3.- Mostrar codigo de salida correcta o incorrecta según caso.
#
#  Codigos de salida:
##	201 - El usuario se ha borrado del grupo de assignatura principal, pero no de todos los grupos_asignatura
#
#       505 - El directorio de la asignatura no existe
#       507 - El grupo local de la asignatura no existe
#       521 - El alumno no puede borrarse del grupo local de la asignatura, motivo desconocido
#	540 - El usuario se ha borrado del grupo de assignatura principal, pero no de todos los grupos de la asignatura
#       599 - Faltan parametros

source /usr/local/sbin/ganesha-config.sh
usuarios="$1"
asignatura="$2"

salida()
{ 
    echo "{" 
    echo "\"codi\":$2," 
    echo "\"message\":\"$1\"," 
    echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\"}" ; 
    echo "},"
} 

 echo "["

	if [[ $usuarios && $asignatura ]]; then
	   for usuario in $usuarios
	      do
	        error="0"

# Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són validas de antemano

               if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
               if [ ! $(getent group "$asignatura") ]; then error=507; fi

# Fin control de errores fatales


		if [ -d "$HOME_GANESHA/$asignatura" ]; then /usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error=521; else error=505; fi

		if [ "$error" -lt "500" ] && [ -d "$HOME_GANESHA/$asignatura" ]; then
		 	cd $HOME_GANESHA"/$asignatura"
			     for directorio_grupo in  $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
				if [ "$(grep $directorio_grupo /etc/group | grep $usuario | wc -l)" -eq "1" ] ; then	
					/usr/sbin/deluser $usuario $directorio_grupo 2>/dev/null 1>/dev/null || error=540;
				fi
		     	     done
		fi
	
	        if [ "$error" -gt "500" ]; then
        	     txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura")"

	        else
	             txt_salida="$txt_salida$(salida "Borrado el profesor \\\"$usuario\\\" de la asignatura \\\"$asignatura\\\"" "200" "$usuario" "$asignatura")"
	        fi

	      done
  	else
		error=599
		txt_salida=$(salida "ERROR" "$error")
	fi


    txt_salida=${txt_salida::-1}
    echo "$txt_salida"
    echo "]"

