#!/bin/bash
#

#  Nombre script: ganesha-set-ldap-info
# 
#  Parámetros de entrada: 
#    $1="nombre" 
#    $2="apellidos"
#    $3="email" 
#
#  Salida en STDOUT (no STDERR): 
#    {
#    "codi":"<codi>", 
#    "message":"<mensaje>", 
#    "json": { "usuario":"<usuario>", "asignatura":"<asignatura>", "grupo_asignatura":"<grupo_asignatura>" }
#
#  Operaciones:
#	1.- Modificar los datos en el ldap
#	2.- Mostrar codigo de salida correcta o incorrecta según caso.
#
#  Codigos de error:
#	541 - No se han podido modicar los atributos en el LDAP

source /usr/local/sbin/ganesha-config.sh
usuario="$1"
nombre="$2"
apellidos="$3"
email="$4"

salida()
{ 
    echo "{" 
    echo "\"codi\":$2," 
    if [ "$2" -eq "200" ]; then
       echo "\"message\":\"$1\","
    else
       codigo_error="codigo_$2"
       echo "\"message\":\"${!codigo_error}\""
    fi
    echo "}"
} 

/usr/sbin/smbldap-usermod -N "$nombre" -S "$apellidos" -M "$email" $1

if [ "$?" -eq "0" ]; then 
   salida "Usuari modificat correctament!" "200"
   exit 0
   else
   salida "541" "541"
   exit 1
fi
